[package]
name = "ex01-generic-t"
version = "0.1.0"
authors = ["David Silva <srdavidsilva@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
